/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author EvMit8495
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        CalculateButton = new javax.swing.JButton();
        Brownsburgers = new javax.swing.JLabel();
        BurgersTextField = new javax.swing.JTextField();
        FriesTextField = new javax.swing.JTextField();
        BurgerLabel = new javax.swing.JLabel();
        FriesLabel = new javax.swing.JLabel();
        SoftDrinksLabel = new javax.swing.JLabel();
        tbtl = new javax.swing.JLabel();
        SoftDrinksTextField = new javax.swing.JTextField();
        TaxLabel = new javax.swing.JLabel();
        FinalTotalLabel = new javax.swing.JLabel();
        TBT = new javax.swing.JLabel();
        Tax = new javax.swing.JLabel();
        FinalTotal = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        edit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 153, 102));

        CalculateButton.setText("Calculate");
        CalculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateButtonActionPerformed(evt);
            }
        });

        Brownsburgers.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        Brownsburgers.setForeground(new java.awt.Color(255, 0, 51));
        Brownsburgers.setText("BROWNS BURGERS");

        BurgersTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BurgersTextFieldActionPerformed(evt);
            }
        });

        FriesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FriesTextFieldActionPerformed(evt);
            }
        });

        BurgerLabel.setText("Burgers");

        FriesLabel.setText("Fries");

        SoftDrinksLabel.setText("Soft Drinks");

        tbtl.setText("Total Before Taxation");

        TaxLabel.setText("Tax");

        FinalTotalLabel.setText("Final Total");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(SoftDrinksTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(FriesTextField)
                    .addComponent(BurgersTextField))
                .addGap(132, 132, 132))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(Brownsburgers))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbtl)
                            .addComponent(TaxLabel)
                            .addComponent(FinalTotalLabel)
                            .addComponent(BurgerLabel)
                            .addComponent(FriesLabel)
                            .addComponent(SoftDrinksLabel))
                        .addGap(114, 114, 114)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FinalTotal)
                            .addComponent(Tax)
                            .addComponent(TBT)))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(CalculateButton)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(Brownsburgers)
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BurgersTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BurgerLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FriesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FriesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SoftDrinksLabel)
                    .addComponent(SoftDrinksTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(CalculateButton)
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtl)
                    .addComponent(TBT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TaxLabel)
                    .addComponent(Tax))
                .addGap(12, 12, 12)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FinalTotalLabel)
                    .addComponent(FinalTotal))
                .addContainerGap())
        );

        file.setText("File");
        MenuBar.add(file);

        edit.setText("Edit");
        MenuBar.add(edit);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CalculateButtonActionPerformed

    private void FriesTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FriesTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FriesTextFieldActionPerformed

    private void BurgersTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BurgersTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BurgersTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Brownsburgers;
    private javax.swing.JLabel BurgerLabel;
    private javax.swing.JTextField BurgersTextField;
    private javax.swing.JButton CalculateButton;
    private javax.swing.JLabel FinalTotal;
    private javax.swing.JLabel FinalTotalLabel;
    private javax.swing.JLabel FriesLabel;
    private javax.swing.JTextField FriesTextField;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JLabel SoftDrinksLabel;
    private javax.swing.JTextField SoftDrinksTextField;
    private javax.swing.JLabel TBT;
    private javax.swing.JLabel Tax;
    private javax.swing.JLabel TaxLabel;
    private javax.swing.JPanel background;
    private javax.swing.JMenu edit;
    private javax.swing.JMenu file;
    private javax.swing.JLabel tbtl;
    // End of variables declaration//GEN-END:variables
}
